---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
    tags.datadoghq.com/env: DEP
    tags.datadoghq.com/service: Order-Service
    tags.datadoghq.com/version: "1"
  namespace: deploy
  
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
        tags.datadoghq.com/env: DEP
        tags.datadoghq.com/service: Order-Service
        tags.datadoghq.com/version: "1"
    spec:
      containers:
        - name: orders
          image: 009543462659.dkr.ecr.ap-northeast-2.amazonaws.com/orders:3.04
          volumeMounts:
            - name: apmsocketpath
              mountPath: /var/run/datadog
            - mountPath: /tmp
              name: tmp-volume
          env:
            - name: JAVA_OPTS
              value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
        
            - name: DD_LOGS_INJECTION
              value: "true"
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 300Mi
          ports:
          - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            capabilities:
              drop:
                - all
              add:
                - NET_BIND_SERVICE
            readOnlyRootFilesystem: true
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - hostPath:
            path: /var/run/datadog/
          name: apmsocketpath
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  annotations:
        prometheus.io/scrape: 'true'
  labels:
    name: orders
  namespace: deploy
  
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: orders
---
